name: CD

on: 
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    
    steps:
    - uses: actions/checkout@v2
      
    - name: install
      run: npm i
    - name: build
      run: npm run build
    - name: Bundle
      run: mkdir ./out && mkdir ./out/react-gotapp &&  mv build ./out/react-gotapp
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.DEPLOY_TOKEN }}
        external_repository: lisperata/lisperata.github.io
        publish_dir: ./out
        publish_branch: master
        keep_files: true